% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
\documentclass[
]{article}
\usepackage{xcolor}
\usepackage[margin=1in]{geometry}
\usepackage{amsmath,amssymb}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx}
\makeatletter
\newsavebox\pandoc@box
\newcommand*\pandocbounded[1]{% scales image to fit in text height/width
  \sbox\pandoc@box{#1}%
  \Gscale@div\@tempa{\textheight}{\dimexpr\ht\pandoc@box+\dp\pandoc@box\relax}%
  \Gscale@div\@tempb{\linewidth}{\wd\pandoc@box}%
  \ifdim\@tempb\p@<\@tempa\p@\let\@tempa\@tempb\fi% select the smaller of both
  \ifdim\@tempa\p@<\p@\scalebox{\@tempa}{\usebox\pandoc@box}%
  \else\usebox{\pandoc@box}%
  \fi%
}
% Set default figure placement to htbp
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\usepackage{bookmark}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  pdftitle={Digital Marketing Campaign Performance Analysis},
  pdfauthor={Eric Turba},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\title{Digital Marketing Campaign Performance Analysis}
\author{Eric Turba}
\date{2026-01-30}

\begin{document}
\maketitle

\section{Digital Marketing Campaign Performance
Analysis}\label{digital-marketing-campaign-performance-analysis}

\subsection{Context and Objective}\label{context-and-objective}

This analysis examines social media campaign data from XYZ company run
on Facebook (Meta). \textbf{Ideally, we would have revenue return data
to calculate the actual ROI of each campaign.} However, since we don't
have this information, we'll treat this problem as a \textbf{cost
optimization exercise.}

Our objectives are:

\begin{itemize}
\tightlist
\item
  Identify and cut campaigns with high spending and low performance
\item
  Discover demographic and segmentation patterns that work
\item
  Recommend adjustments to maximize investment efficiency
\end{itemize}

The file contains 1,143 observations distributed across 11 variables:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  \textbf{ad\_id}: Unique identifier for each ad
\item
  \textbf{xyz\_campaign\_id}: XYZ company campaign ID
\item
  \textbf{fb\_campaign\_id}: Facebook campaign tracking ID
\item
  \textbf{age}: Target audience age range
\item
  \textbf{gender}: Target audience gender
\item
  \textbf{interest}: Interest category code
\item
  \textbf{Impressions}: Total number of times the ad was shown
\item
  \textbf{Clicks}: Total number of times users clicked on the ad
\item
  \textbf{Spent}: Total amount of money invested by XYZ Company to run
  the ad
\item
  \textbf{Total\_Conversion}: Total number of people who showed interest
  in the product after viewing the ad
\item
  \textbf{Approved\_Conversion}: Total number of people who completed a
  purchase after engaging with the ad
\end{enumerate}

First, we will load the necessary libraries for this project:

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Loading Libraries}
\FunctionTok{library}\NormalTok{(readr)}
\FunctionTok{library}\NormalTok{(tidyverse)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## -- Attaching core tidyverse packages ------------------------ tidyverse 2.0.0 --
## v dplyr     1.1.4     v purrr     1.1.0
## v forcats   1.0.1     v stringr   1.5.2
## v ggplot2   4.0.0     v tibble    3.3.0
## v lubridate 1.9.4     v tidyr     1.3.1
## -- Conflicts ------------------------------------------ tidyverse_conflicts() --
## x dplyr::filter() masks stats::filter()
## x dplyr::lag()    masks stats::lag()
## i Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(ggplot2)}
\FunctionTok{library}\NormalTok{(skimr)}
\FunctionTok{library}\NormalTok{(DataExplorer)}
\FunctionTok{library}\NormalTok{(gridExtra)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Attaching package: 'gridExtra'
## 
## The following object is masked from 'package:dplyr':
## 
##     combine
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(scales)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Attaching package: 'scales'
## 
## The following object is masked from 'package:purrr':
## 
##     discard
## 
## The following object is masked from 'package:readr':
## 
##     col_factor
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(colorspace)}
\end{Highlighting}
\end{Shaded}

Next, we'll standardize plot dimensions to a default width and height to
improve readability and visual clarity

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{options}\NormalTok{(}\AttributeTok{repr.plot.width =} \DecValTok{15}\NormalTok{, }\AttributeTok{repr.plot.height =} \DecValTok{10}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

Before we start the analysis, we will create a conversion funnel. The
following source was used to assist in the creation process:
\url{https://gist.github.com/jjesusfilho/fd14b58becab4924befef5be239c6011}

This funnel will be used to visually represent how users move through
different stages of a digital marketing campaign, for example, from
seeing an ad (impressions) to clicking it, showing interest, and finally
making a purchase. This type of visualization helps quickly identify
where audience drop-offs occur in the conversion process, making it
easier to pinpoint inefficiencies in campaign performance.

We will utilize this funnel later in our analysis.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Function to create conversion funnel charts}
\CommentTok{\# Source: https://gist.github.com/jjesusfilho/fd14b58becab4924befef5be239c6011}

\NormalTok{gg\_funnel }\OtherTok{\textless{}{-}} \ControlFlowTok{function}\NormalTok{(x, }\AttributeTok{text =} \ConstantTok{NULL}\NormalTok{, }\AttributeTok{color =} \ConstantTok{NULL}\NormalTok{, }\AttributeTok{lbl\_size =} \DecValTok{4}\NormalTok{)\{}
  
  \DocumentationTok{\#\#\# Type Validation }\AlertTok{\#\#\#}
  \ControlFlowTok{if}\NormalTok{ (}\SpecialCharTok{!}\FunctionTok{is.numeric}\NormalTok{(x))\{}
    \FunctionTok{stop}\NormalTok{(}\StringTok{"x must be a numeric vector"}\NormalTok{)}
\NormalTok{  \}}
  
  \ControlFlowTok{if}\NormalTok{ (}\FunctionTok{any}\NormalTok{(x }\SpecialCharTok{\textless{}} \DecValTok{0}\NormalTok{))\{}
    \FunctionTok{stop}\NormalTok{(}\StringTok{"This function does not accept negative values"}\NormalTok{)}
\NormalTok{  \}}
  
\NormalTok{  x }\OtherTok{\textless{}{-}} \FunctionTok{sort}\NormalTok{(x, }\AttributeTok{decreasing =} \ConstantTok{TRUE}\NormalTok{)}
  
  \ControlFlowTok{if}\NormalTok{ (}\FunctionTok{is.null}\NormalTok{(color))\{}
\NormalTok{    color }\OtherTok{\textless{}{-}}\NormalTok{ colorspace}\SpecialCharTok{::}\FunctionTok{qualitative\_hcl}\NormalTok{(}\FunctionTok{length}\NormalTok{(x), }\AttributeTok{palette =} \StringTok{"Dark 3"}\NormalTok{)}
\NormalTok{  \}}
  
  \ControlFlowTok{if}\NormalTok{ (}\FunctionTok{is.null}\NormalTok{(text))\{}
\NormalTok{    text }\OtherTok{\textless{}{-}} \FunctionTok{as.character}\NormalTok{(x)}
\NormalTok{  \}}
  
  \ControlFlowTok{if}\NormalTok{(}\SpecialCharTok{!}\FunctionTok{all.equal}\NormalTok{(}\FunctionTok{length}\NormalTok{(x), }\FunctionTok{length}\NormalTok{(text), }\FunctionTok{length}\NormalTok{(color)))\{}
    \FunctionTok{stop}\NormalTok{(}\StringTok{"x, text, and color must have the same length"}\NormalTok{)}
\NormalTok{  \}}
  
  \DocumentationTok{\#\#\# Create x coordinates }\AlertTok{\#\#\#}
\NormalTok{  l1 }\OtherTok{\textless{}{-}} \FunctionTok{vector}\NormalTok{(}\StringTok{"list"}\NormalTok{, }\FunctionTok{length}\NormalTok{(x))}
  
  \ControlFlowTok{for}\NormalTok{ (i }\ControlFlowTok{in} \DecValTok{1}\SpecialCharTok{:}\FunctionTok{length}\NormalTok{(x))\{}
    \ControlFlowTok{if}\NormalTok{ (i }\SpecialCharTok{==} \DecValTok{1}\NormalTok{)\{}
\NormalTok{      x3 }\OtherTok{\textless{}{-}}\NormalTok{ x[}\DecValTok{1}\NormalTok{]}
\NormalTok{      x4 }\OtherTok{\textless{}{-}} \DecValTok{0}
\NormalTok{      x1 }\OtherTok{\textless{}{-}} \FunctionTok{seq}\NormalTok{(x4, x3, }\AttributeTok{length.out =} \DecValTok{6}\NormalTok{)[}\DecValTok{2}\NormalTok{]}
\NormalTok{      x2 }\OtherTok{\textless{}{-}} \FunctionTok{seq}\NormalTok{(x4, x3, }\AttributeTok{length.out =} \DecValTok{6}\NormalTok{)[}\DecValTok{5}\NormalTok{]}
\NormalTok{    \} }\ControlFlowTok{else}\NormalTok{ \{}
\NormalTok{      x4 }\OtherTok{\textless{}{-}}\NormalTok{ l1[[i}\DecValTok{{-}1}\NormalTok{]][}\DecValTok{1}\NormalTok{]}
\NormalTok{      x3 }\OtherTok{\textless{}{-}}\NormalTok{ l1[[i}\DecValTok{{-}1}\NormalTok{]][}\DecValTok{2}\NormalTok{]}
\NormalTok{      x1 }\OtherTok{\textless{}{-}} \FunctionTok{seq}\NormalTok{(x4, x3, }\AttributeTok{length.out =} \DecValTok{6}\NormalTok{)[}\DecValTok{2}\NormalTok{]}
\NormalTok{      x2 }\OtherTok{\textless{}{-}} \FunctionTok{seq}\NormalTok{(x4, x3, }\AttributeTok{length.out =} \DecValTok{6}\NormalTok{)[}\DecValTok{5}\NormalTok{]}
\NormalTok{    \}}
    
\NormalTok{    l1[[i]] }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(x1, x2, x3, x4)}
\NormalTok{  \}}
    
  \DocumentationTok{\#\#\# Create y coordinates }\AlertTok{\#\#\#}
\NormalTok{  l2 }\OtherTok{\textless{}{-}}\NormalTok{ purrr}\SpecialCharTok{::}\FunctionTok{map}\NormalTok{(}\FunctionTok{length}\NormalTok{(x)}\SpecialCharTok{:}\DecValTok{1}\NormalTok{, }\SpecialCharTok{\textasciitilde{}}\NormalTok{\{}
    \FunctionTok{c}\NormalTok{(.x}\SpecialCharTok{*}\DecValTok{5{-}5}\NormalTok{, .x}\SpecialCharTok{*}\DecValTok{5{-}5}\NormalTok{, .x}\SpecialCharTok{*}\DecValTok{5}\NormalTok{, .x}\SpecialCharTok{*}\DecValTok{5}\NormalTok{)}
\NormalTok{  \})}
  
  \DocumentationTok{\#\# Create data.frame based on coordinates }\AlertTok{\#\#\#}
\NormalTok{  dfs }\OtherTok{\textless{}{-}}\NormalTok{ purrr}\SpecialCharTok{::}\FunctionTok{map2}\NormalTok{(l1, l2, }\SpecialCharTok{\textasciitilde{}}\NormalTok{\{}
    \FunctionTok{data.frame}\NormalTok{(}\AttributeTok{x =}\NormalTok{ .x, }\AttributeTok{y =}\NormalTok{ .y)}
\NormalTok{  \})}
  
  \DocumentationTok{\#\#\# Create individual plots and stack them }\AlertTok{\#\#\#}
\NormalTok{  p }\OtherTok{\textless{}{-}}\NormalTok{ ggplot2}\SpecialCharTok{::}\FunctionTok{ggplot}\NormalTok{()}
  
  \ControlFlowTok{for}\NormalTok{ (i }\ControlFlowTok{in} \DecValTok{1}\SpecialCharTok{:}\FunctionTok{length}\NormalTok{(dfs))\{}
\NormalTok{    p}\OtherTok{\textless{}{-}}\NormalTok{ p }\SpecialCharTok{+}
\NormalTok{      ggplot2}\SpecialCharTok{::}\FunctionTok{geom\_polygon}\NormalTok{(}\AttributeTok{data =}\NormalTok{ dfs[[i]], ggplot2}\SpecialCharTok{::}\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ x, }\AttributeTok{y =}\NormalTok{ y),}
                            \AttributeTok{fill =}\NormalTok{ color[i]) }\SpecialCharTok{+}
\NormalTok{      ggplot2}\SpecialCharTok{::}\FunctionTok{annotate}\NormalTok{(}\StringTok{"text"}\NormalTok{, }\AttributeTok{label =}\NormalTok{ text[i], }\AttributeTok{x =}\NormalTok{ x[}\DecValTok{1}\NormalTok{]}\SpecialCharTok{/}\DecValTok{2}\NormalTok{,}
                        \AttributeTok{y =} \FunctionTok{mean}\NormalTok{(dfs[[i]]}\SpecialCharTok{$}\NormalTok{y),}
                        \AttributeTok{size =}\NormalTok{ lbl\_size,}
                        \AttributeTok{fontface =} \StringTok{"bold"}\NormalTok{,}
                        \AttributeTok{color =} \StringTok{"black"}\NormalTok{) }\SpecialCharTok{+}
\NormalTok{      ggplot2}\SpecialCharTok{::}\FunctionTok{theme\_minimal}\NormalTok{() }\SpecialCharTok{+}
\NormalTok{      ggplot2}\SpecialCharTok{::}\FunctionTok{theme}\NormalTok{(}
        \AttributeTok{axis.title =}\NormalTok{ ggplot2}\SpecialCharTok{::}\FunctionTok{element\_blank}\NormalTok{(),}
        \AttributeTok{axis.text =}\NormalTok{ ggplot2}\SpecialCharTok{::}\FunctionTok{element\_blank}\NormalTok{(),}
        \AttributeTok{axis.ticks =}\NormalTok{ ggplot2}\SpecialCharTok{::}\FunctionTok{element\_blank}\NormalTok{(),}
        \AttributeTok{panel.grid =}\NormalTok{ ggplot2}\SpecialCharTok{::}\FunctionTok{element\_blank}\NormalTok{()}
\NormalTok{      )}
\NormalTok{  \}}
    
\NormalTok{    p}
\NormalTok{\}}
\end{Highlighting}
\end{Shaded}

Once the funnel is created, we will now load the data.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Loading data}
\NormalTok{df }\OtherTok{\textless{}{-}} \FunctionTok{read\_csv}\NormalTok{(}\StringTok{"KAG\_conversion\_data.csv"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Rows: 1143 Columns: 11
## -- Column specification --------------------------------------------------------
## Delimiter: ","
## chr (2): age, gender
## dbl (9): ad_id, xyz_campaign_id, fb_campaign_id, interest, Impressions, Clic...
## 
## i Use `spec()` to retrieve the full column specification for this data.
## i Specify the column types or set `show_col_types = FALSE` to quiet this message.
\end{verbatim}

The next few steps will allow us to get an introduction into the data
set.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Data structure overview}
\FunctionTok{glimpse}\NormalTok{(df)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Rows: 1,143
## Columns: 11
## $ ad_id               <dbl> 708746, 708749, 708771, 708815, 708818, 708820, 70~
## $ xyz_campaign_id     <dbl> 916, 916, 916, 916, 916, 916, 916, 916, 916, 916, ~
## $ fb_campaign_id      <dbl> 103916, 103917, 103920, 103928, 103928, 103929, 10~
## $ age                 <chr> "30-34", "30-34", "30-34", "30-34", "30-34", "30-3~
## $ gender              <chr> "M", "M", "M", "M", "M", "M", "M", "M", "M", "M", ~
## $ interest            <dbl> 15, 16, 20, 28, 28, 29, 15, 16, 27, 28, 31, 7, 16,~
## $ Impressions         <dbl> 7350, 17861, 693, 4259, 4133, 1915, 15615, 10951, ~
## $ Clicks              <dbl> 1, 2, 0, 1, 1, 0, 3, 1, 1, 3, 0, 0, 0, 0, 7, 0, 1,~
## $ Spent               <dbl> 1.43, 1.82, 0.00, 1.25, 1.29, 0.00, 4.77, 1.27, 1.~
## $ Total_Conversion    <dbl> 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,~
## $ Approved_Conversion <dbl> 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0,~
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# First rows of the dataset}
\FunctionTok{head}\NormalTok{(df)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 6 x 11
##    ad_id xyz_campaign_id fb_campaign_id age   gender interest Impressions Clicks
##    <dbl>           <dbl>          <dbl> <chr> <chr>     <dbl>       <dbl>  <dbl>
## 1 708746             916         103916 30-34 M            15        7350      1
## 2 708749             916         103917 30-34 M            16       17861      2
## 3 708771             916         103920 30-34 M            20         693      0
## 4 708815             916         103928 30-34 M            28        4259      1
## 5 708818             916         103928 30-34 M            28        4133      1
## 6 708820             916         103929 30-34 M            29        1915      0
## # i 3 more variables: Spent <dbl>, Total_Conversion <dbl>,
## #   Approved_Conversion <dbl>
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Complete statistical summary}
\NormalTok{df }\SpecialCharTok{\%\textgreater{}\%}\NormalTok{ skimr}\SpecialCharTok{::}\FunctionTok{skim}\NormalTok{() }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{print}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## -- Data Summary ------------------------
##                            Values    
## Name                       Piped data
## Number of rows             1143      
## Number of columns          11        
## _______________________              
## Column type frequency:               
##   character                2         
##   numeric                  9         
## ________________________             
## Group variables            None      
## 
## -- Variable type: character ----------------------------------------------------
##   skim_variable n_missing complete_rate min max empty n_unique whitespace
## 1 age                   0             1   5   5     0        4          0
## 2 gender                0             1   1   1     0        2          0
## 
## -- Variable type: numeric ------------------------------------------------------
##   skim_variable       n_missing complete_rate       mean        sd     p0
## 1 ad_id                       0             1 987261.    193993.   708746
## 2 xyz_campaign_id             0             1   1067.       122.      916
## 3 fb_campaign_id              0             1 133784.     20500.   103916
## 4 interest                    0             1     32.8       27.0       2
## 5 Impressions                 0             1 186732.    312762.       87
## 6 Clicks                      0             1     33.4       56.9       0
## 7 Spent                       0             1     51.4       86.9       0
## 8 Total_Conversion            0             1      2.86       4.48      0
## 9 Approved_Conversion         0             1      0.944      1.74      0
##         p25       p50       p75     p100 hist 
## 1 777632.   1121185   1121804.  1314415  ▆▁▁▇▂
## 2    936       1178      1178      1178  ▆▁▁▁▇
## 3 115716     144549    144658.   179982  ▆▁▇▁▂
## 4     16         25        31       114  ▇▅▂▁▂
## 5   6504.     51509    221769   3052003  ▇▁▁▁▁
## 6      1          8        37.5     421  ▇▁▁▁▁
## 7      1.48      12.4      60.0     640. ▇▁▁▁▁
## 8      1          1         3        60  ▇▁▁▁▁
## 9      0          1         1        21  ▇▁▁▁▁
\end{verbatim}

Now let's get an introductory visualization of data quality.

This plot tells us how many variables are continuous versus discrete and
what proportion of rows and cells contain missing values. This will
serve as an initial data quality check before getting into exploratory
analysis.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Introductory visualization of data quality }
\FunctionTok{plot\_intro}\NormalTok{(df)}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{Digital-Marketing-Analysis-RMD_files/figure-latex/8-1.pdf}}

To begin our exploratory analysis, let's look at the distribution of ads
by campaign:

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Distribution of ads by campaign}
\NormalTok{df }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{group\_by}\NormalTok{(xyz\_campaign\_id) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{summarise}\NormalTok{(}\AttributeTok{total =} \FunctionTok{n}\NormalTok{())}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 3 x 2
##   xyz_campaign_id total
##             <dbl> <int>
## 1             916    54
## 2             936   464
## 3            1178   625
\end{verbatim}

\subsection{Exploratory Analysis: Distribution by
Campaign}\label{exploratory-analysis-distribution-by-campaign}

We observe that \textbf{Campaign 916} had a much lower volume of ads
compared to the others, while \textbf{Campaign 1178} had the most ads.
\textbf{Campaign 916} only having \textbf{54} ads seems like an outlier
compared to \textbf{Campaign 936} and \textbf{Campaign 1178} which had
\textbf{464} and \textbf{625} ads respectfully.

Let's investigate how age groups are distributed in the database and how
they fare in each campaign.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# General distribution by age range}
\NormalTok{df }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{group\_by}\NormalTok{(age) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{summarise}\NormalTok{(}\AttributeTok{total =} \FunctionTok{n}\NormalTok{())}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 4 x 2
##   age   total
##   <chr> <int>
## 1 30-34   426
## 2 35-39   248
## 3 40-44   210
## 4 45-49   259
\end{verbatim}

\subsection{Age Concentration}\label{age-concentration}

Approximately \textbf{60\% of the database} is concentrated in the
\textbf{30-39 years} range with the age range between \textbf{30-34}
being the highest at \textbf{426}.

How are these groups distributed when we consider each campaign
individually?

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Age distribution by campaign}
\NormalTok{df }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{group\_by}\NormalTok{(xyz\_campaign\_id, age) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{summarise}\NormalTok{(}\AttributeTok{total =} \FunctionTok{n}\NormalTok{(), }\AttributeTok{.groups =} \StringTok{"drop\_last"}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{mutate}\NormalTok{(}\AttributeTok{percentage =} \FunctionTok{round}\NormalTok{(total }\SpecialCharTok{*} \DecValTok{100} \SpecialCharTok{/} \FunctionTok{sum}\NormalTok{(total), }\DecValTok{2}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 12 x 4
## # Groups:   xyz_campaign_id [3]
##    xyz_campaign_id age   total percentage
##              <dbl> <chr> <int>      <dbl>
##  1             916 30-34    29       53.7
##  2             916 35-39    12       22.2
##  3             916 40-44     6       11.1
##  4             916 45-49     7       13.0
##  5             936 30-34   196       42.2
##  6             936 35-39    89       19.2
##  7             936 40-44    75       16.2
##  8             936 45-49   104       22.4
##  9            1178 30-34   201       32.2
## 10            1178 35-39   147       23.5
## 11            1178 40-44   129       20.6
## 12            1178 45-49   148       23.7
\end{verbatim}

\subsection{Age Segmentation Pattern}\label{age-segmentation-pattern}

All campaigns focus predominantly on the \textbf{30-34 years} range,
with the difference being less pronounced in \textbf{Campaign 1178}
where \textbf{32.2\%} of ads were focused on that age range which is the
lowest percentage compared to the other two campaigns.

Now let's analyze how genders are distributed when we consider campaign
and age range simultaneously.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# General distribution by gender}
\NormalTok{df }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{group\_by}\NormalTok{(gender) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{summarise}\NormalTok{(}\AttributeTok{total =} \FunctionTok{n}\NormalTok{())}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 2 x 2
##   gender total
##   <chr>  <int>
## 1 F        551
## 2 M        592
\end{verbatim}

\subsection{Gender Balance}\label{gender-balance}

The distribution between genders is quite balanced, with a slightly
higher numbers of ads going towards the \textbf{male} audience.

Now let's break it down by campaign.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Gender distribution by campaign}
\NormalTok{df }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{group\_by}\NormalTok{(xyz\_campaign\_id, gender) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{summarise}\NormalTok{(}\AttributeTok{total =} \FunctionTok{n}\NormalTok{(), }\AttributeTok{.groups =} \StringTok{"drop\_last"}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{mutate}\NormalTok{(}\AttributeTok{percentage =} \FunctionTok{round}\NormalTok{(total }\SpecialCharTok{*} \DecValTok{100} \SpecialCharTok{/} \FunctionTok{sum}\NormalTok{(total), }\DecValTok{2}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 6 x 4
## # Groups:   xyz_campaign_id [3]
##   xyz_campaign_id gender total percentage
##             <dbl> <chr>  <int>      <dbl>
## 1             916 F         19       35.2
## 2             916 M         35       64.8
## 3             936 F        256       55.2
## 4             936 M        208       44.8
## 5            1178 F        276       44.2
## 6            1178 M        349       55.8
\end{verbatim}

\subsection{Difference in Campaign
936}\label{difference-in-campaign-936}

Only \textbf{Campaign 936} shows a higher overall percentage of
\textbf{women} with \textbf{55.2\%} of ads being directed towards
\textbf{women}.

What if we include age ranges in this analysis?

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Visualization: Gender distribution by age and campaign}
\NormalTok{df }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{group\_by}\NormalTok{(xyz\_campaign\_id, age, gender) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{summarise}\NormalTok{(}\AttributeTok{total =} \FunctionTok{n}\NormalTok{(), }\AttributeTok{.groups =} \StringTok{"drop\_last"}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{mutate}\NormalTok{(}\AttributeTok{percentage =} \FunctionTok{round}\NormalTok{(total }\SpecialCharTok{*} \DecValTok{100} \SpecialCharTok{/} \FunctionTok{sum}\NormalTok{(total), }\DecValTok{2}\NormalTok{)) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{ggplot}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ age, }\AttributeTok{y =}\NormalTok{ percentage, }\AttributeTok{fill =}\NormalTok{ gender)) }\SpecialCharTok{+}
  \FunctionTok{geom\_col}\NormalTok{() }\SpecialCharTok{+}
  \FunctionTok{geom\_text}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{label =} \FunctionTok{paste0}\NormalTok{(percentage, }\StringTok{"\%"}\NormalTok{)),}
            \AttributeTok{position =} \FunctionTok{position\_stack}\NormalTok{(}\AttributeTok{vjust =} \FloatTok{0.5}\NormalTok{), }\AttributeTok{size =} \DecValTok{3}\NormalTok{, }\AttributeTok{color =} \StringTok{"white"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{facet\_wrap}\NormalTok{(}\SpecialCharTok{\textasciitilde{}}\NormalTok{ xyz\_campaign\_id) }\SpecialCharTok{+}
  \FunctionTok{scale\_fill\_brewer}\NormalTok{(}\AttributeTok{palette =} \StringTok{"Set2"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}
    \AttributeTok{title =} \StringTok{"Gender Distribution by Age and Campaign"}\NormalTok{,}
    \AttributeTok{y =} \StringTok{"Proportion (\%)"}\NormalTok{,}
    \AttributeTok{x =} \StringTok{"Age Range"}
\NormalTok{  ) }\SpecialCharTok{+}
  \FunctionTok{theme\_minimal}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{Digital-Marketing-Analysis-RMD_files/figure-latex/14-1.pdf}}

\textbf{Campaign 936} was spread out evenly for \textbf{men} and
\textbf{women} in the age range \textbf{30-34} but targeted more
\textbf{women} in all other age categories.

\textbf{Campaign 1178} had a fairly even gender spread across age ranges
with about \textbf{55\%} of ads being directed towards \textbf{men} in
each age range.

\subsection{Introduction of Performance
Metrics}\label{introduction-of-performance-metrics}

Now let's calculate standard digital marketing metrics:

\begin{itemize}
\tightlist
\item
  \textbf{CTR(Click-Through Rate)}: The percentage of users who click on
  an ad after seeing it.
\item
  \textbf{CPC(Cost Per Click)}: The average amount paid each time a user
  clicks on an ad.
\item
  \textbf{CPA(Cost Per Acquisition)}: The average cost incurred for each
  completed conversion or sale.
\end{itemize}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Performance metrics calculation}
\NormalTok{df }\OtherTok{\textless{}{-}}\NormalTok{ df }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{mutate}\NormalTok{(}
    \AttributeTok{CTR =} \FunctionTok{ifelse}\NormalTok{(Impressions }\SpecialCharTok{\textgreater{}} \DecValTok{0}\NormalTok{, (Clicks }\SpecialCharTok{/}\NormalTok{ Impressions) }\SpecialCharTok{*} \DecValTok{100}\NormalTok{, }\ConstantTok{NA}\NormalTok{),}
    \AttributeTok{CPC =} \FunctionTok{ifelse}\NormalTok{(Clicks }\SpecialCharTok{\textgreater{}} \DecValTok{0}\NormalTok{, Spent }\SpecialCharTok{/}\NormalTok{ Clicks, }\ConstantTok{NA}\NormalTok{),}
    \AttributeTok{CPA =} \FunctionTok{ifelse}\NormalTok{(Approved\_Conversion }\SpecialCharTok{\textgreater{}} \DecValTok{0}\NormalTok{, Spent }\SpecialCharTok{/}\NormalTok{ Approved\_Conversion, }\ConstantTok{NA}\NormalTok{)         }
\NormalTok{  )}
\end{Highlighting}
\end{Shaded}

Let's first verify that the columns have been created correctly:

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Verification of new columns}
\FunctionTok{head}\NormalTok{(df, }\DecValTok{3}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 3 x 14
##    ad_id xyz_campaign_id fb_campaign_id age   gender interest Impressions Clicks
##    <dbl>           <dbl>          <dbl> <chr> <chr>     <dbl>       <dbl>  <dbl>
## 1 708746             916         103916 30-34 M            15        7350      1
## 2 708749             916         103917 30-34 M            16       17861      2
## 3 708771             916         103920 30-34 M            20         693      0
## # i 6 more variables: Spent <dbl>, Total_Conversion <dbl>,
## #   Approved_Conversion <dbl>, CTR <dbl>, CPC <dbl>, CPA <dbl>
\end{verbatim}

Now we will aggregate the performance metrics for each campaign in the
data set and then we will create a series of funnel plots to visualize
the performance of each campaign using the gg\_funnel function that we
created earlier.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Metrics aggregation by campaign }
\NormalTok{df\_performance }\OtherTok{\textless{}{-}}\NormalTok{ df }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{group\_by}\NormalTok{(xyz\_campaign\_id) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{summarise}\NormalTok{(}
    \AttributeTok{ads\_run =} \FunctionTok{n\_distinct}\NormalTok{(ad\_id),}
    \AttributeTok{investment =} \FunctionTok{sum}\NormalTok{(Spent),}
    \AttributeTok{impressions =} \FunctionTok{sum}\NormalTok{(Impressions),}
    \AttributeTok{clicks =} \FunctionTok{sum}\NormalTok{(Clicks),}
    \AttributeTok{leads =} \FunctionTok{sum}\NormalTok{(Total\_Conversion),}
    \AttributeTok{sales =} \FunctionTok{sum}\NormalTok{(Approved\_Conversion),}
    \AttributeTok{ctr\_global =}\NormalTok{ (clicks }\SpecialCharTok{/}\NormalTok{ impressions) }\SpecialCharTok{*} \DecValTok{100}\NormalTok{,}
    \AttributeTok{cpc\_global =}\NormalTok{ investment }\SpecialCharTok{/}\NormalTok{ clicks,}
    \AttributeTok{lead\_to\_sale\_rate =}\NormalTok{ (sales }\SpecialCharTok{/}\NormalTok{ leads) }\SpecialCharTok{*} \DecValTok{100}\NormalTok{,}
    \AttributeTok{cpa\_global =}\NormalTok{ investment }\SpecialCharTok{/}\NormalTok{ sales,}
    \AttributeTok{.groups =} \StringTok{"drop"}
\NormalTok{  )}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{plot\_list }\OtherTok{\textless{}{-}} \FunctionTok{list}\NormalTok{()}

\ControlFlowTok{for}\NormalTok{(campaign }\ControlFlowTok{in} \FunctionTok{unique}\NormalTok{(df\_performance}\SpecialCharTok{$}\NormalTok{xyz\_campaign\_id)) \{}
  
\NormalTok{  campaign\_data }\OtherTok{\textless{}{-}}\NormalTok{ df\_performance }\SpecialCharTok{\%\textgreater{}\%} 
    \FunctionTok{filter}\NormalTok{(xyz\_campaign\_id }\SpecialCharTok{==}\NormalTok{ campaign)}
  
\NormalTok{  funnel\_vec }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}
\NormalTok{  campaign\_data}\SpecialCharTok{$}\NormalTok{impressions,}
\NormalTok{  campaign\_data}\SpecialCharTok{$}\NormalTok{clicks,}
\NormalTok{  campaign\_data}\SpecialCharTok{$}\NormalTok{leads,}
\NormalTok{  campaign\_data}\SpecialCharTok{$}\NormalTok{sales}
\NormalTok{  )}
  
\NormalTok{texts}\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}
  \FunctionTok{paste0}\NormalTok{(}\StringTok{"Imp: "}\NormalTok{, scales}\SpecialCharTok{::}\FunctionTok{comma}\NormalTok{(funnel\_vec[}\DecValTok{1}\NormalTok{])),}
  \FunctionTok{paste0}\NormalTok{(}\StringTok{"Clicks: "}\NormalTok{, scales}\SpecialCharTok{::}\FunctionTok{comma}\NormalTok{(funnel\_vec[}\DecValTok{2}\NormalTok{]), }\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{("}\NormalTok{,}
         \FunctionTok{round}\NormalTok{(funnel\_vec[}\DecValTok{2}\NormalTok{]}\SpecialCharTok{/}\NormalTok{funnel\_vec[}\DecValTok{1}\NormalTok{]}\SpecialCharTok{*}\DecValTok{100}\NormalTok{, }\DecValTok{2}\NormalTok{), }\StringTok{"\%)"}\NormalTok{),}
  \FunctionTok{paste0}\NormalTok{(}\StringTok{"Leads: "}\NormalTok{, funnel\_vec[}\DecValTok{3}\NormalTok{], }\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{("}\NormalTok{,}
         \FunctionTok{round}\NormalTok{(funnel\_vec[}\DecValTok{3}\NormalTok{]}\SpecialCharTok{/}\NormalTok{funnel\_vec[}\DecValTok{2}\NormalTok{]}\SpecialCharTok{*}\DecValTok{100}\NormalTok{, }\DecValTok{2}\NormalTok{), }\StringTok{"\%)"}\NormalTok{),}
  \FunctionTok{paste0}\NormalTok{(}\StringTok{"Sales: "}\NormalTok{, funnel\_vec[}\DecValTok{4}\NormalTok{], }\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{("}\NormalTok{,}
         \FunctionTok{round}\NormalTok{(funnel\_vec[}\DecValTok{4}\NormalTok{]}\SpecialCharTok{/}\NormalTok{funnel\_vec[}\DecValTok{3}\NormalTok{]}\SpecialCharTok{*}\DecValTok{100}\NormalTok{, }\DecValTok{2}\NormalTok{), }\StringTok{"\%)"}\NormalTok{)}
\NormalTok{)}

\NormalTok{p }\OtherTok{\textless{}{-}} \FunctionTok{gg\_funnel}\NormalTok{(funnel\_vec, }\AttributeTok{text =}\NormalTok{ texts) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}
    \AttributeTok{title =} \FunctionTok{paste}\NormalTok{(}\StringTok{"Campaign"}\NormalTok{, campaign),}
    \AttributeTok{subtitle =} \FunctionTok{paste}\NormalTok{(}\StringTok{"CPA: $"}\NormalTok{, }\FunctionTok{round}\NormalTok{(campaign\_data}\SpecialCharTok{$}\NormalTok{cpa\_global, }\DecValTok{2}\NormalTok{))}
\NormalTok{  ) }\SpecialCharTok{+}
  \FunctionTok{theme}\NormalTok{(}
    \AttributeTok{plot.title =} \FunctionTok{element\_text}\NormalTok{(}\AttributeTok{size =} \DecValTok{16}\NormalTok{, }\AttributeTok{face =} \StringTok{"bold"}\NormalTok{, }\AttributeTok{hjust =} \FloatTok{0.5}\NormalTok{),}
    \AttributeTok{plot.subtitle =} \FunctionTok{element\_text}\NormalTok{(}\AttributeTok{size =} \DecValTok{12}\NormalTok{, }\AttributeTok{hjust =} \FloatTok{0.5}\NormalTok{),}
    \AttributeTok{axis.text =} \FunctionTok{element\_text}\NormalTok{(}\AttributeTok{size =} \DecValTok{12}\NormalTok{),}
    \AttributeTok{axis.title =} \FunctionTok{element\_text}\NormalTok{(}\AttributeTok{size =} \DecValTok{14}\NormalTok{)}
\NormalTok{  )}
  
\NormalTok{plot\_list[[}\FunctionTok{as.character}\NormalTok{(campaign)]] }\OtherTok{\textless{}{-}}\NormalTok{ p}
\NormalTok{\}}

\FunctionTok{grid.arrange}\NormalTok{(}\AttributeTok{grobs =}\NormalTok{ plot\_list, }\AttributeTok{ncol =} \DecValTok{3}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{Digital-Marketing-Analysis-RMD_files/figure-latex/18-1.pdf}}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Performance summary table}
\FunctionTok{print}\NormalTok{(df\_performance)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 3 x 11
##   xyz_campaign_id ads_run investment impressions clicks leads sales ctr_global
##             <dbl>   <int>      <dbl>       <dbl>  <dbl> <dbl> <dbl>      <dbl>
## 1             916      54       150.      482925    113    58    24     0.0234
## 2             936     464      2893.     8128187   1984   537   183     0.0244
## 3            1178     625     55662.   204823716  36068  2669   872     0.0176
## # i 3 more variables: cpc_global <dbl>, lead_to_sale_rate <dbl>,
## #   cpa_global <dbl>
\end{verbatim}

\subsection{Preliminary Performance
Insights}\label{preliminary-performance-insights}

\textbf{Campaign 916}: Shows low relative investment and few ads run,
but has the \textbf{best lead→sale conversion rate} and consequently the
\textbf{lowest CPA}. This may be the result of efficient segmentation,
good niche choice (interest) or simply statistical luck. Given the small
sample size (compared to the other campaigns) it is tough to come away
with any conclusions.

\textbf{Campaign 1178}: Shows a huge investment was done for the
campaign and in turn, generated by far the most \textbf{impressions,
clicks, leads, and sales} compared to the other campaigns. However,
\textbf{Campaign 1178} also showed a \textbf{CPA over 4x worse} than
other campaigns. The campaign did have a similar \textbf{lead→sale
conversion rate} compared to \textbf{Campaign 936} at \textbf{32.67\%}.

\subsubsection{Question to Investigate:}\label{question-to-investigate}

\begin{itemize}
\tightlist
\item
  Are there differences in interests that were targeted in
  \textbf{Campaign 916} compared to the interests that were targeted in
  \textbf{Campaign 1178}?
\item
  In \textbf{Campaign 1178}, did some ads perform well but were ``pulled
  down'' by others resulting in the higher CPA?
\item
  Are there specific patterns of \textbf{interests} and \textbf{ages}
  that explain the differences between the success of one ad to the
  next?
\end{itemize}

To further our analysis, let's group the ads based on interest and
campaign and then we'll aggregate the performance metrics.

Then, we'll create a matrix style graph which shows the sales volume and
CPA for interest code in each ad campaign. The goal is to understand
\textbf{where campaigns invested, which interests generated sales, and
how cost-efficient those investments were}.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Performance analysis by interest and campaign}
\NormalTok{interest\_analysis }\OtherTok{\textless{}{-}}\NormalTok{ df }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{mutate}\NormalTok{(}\AttributeTok{xyz\_campaign\_id =} \FunctionTok{as.character}\NormalTok{(xyz\_campaign\_id)) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{group\_by}\NormalTok{(interest, xyz\_campaign\_id) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{summarise}\NormalTok{(}
    \AttributeTok{sales =} \FunctionTok{sum}\NormalTok{(Approved\_Conversion),}
    \AttributeTok{cpa =} \FunctionTok{sum}\NormalTok{(Spent) }\SpecialCharTok{/} \FunctionTok{sum}\NormalTok{(Approved\_Conversion),}
    \AttributeTok{.groups =} \StringTok{"drop"}
\NormalTok{  ) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{filter}\NormalTok{(sales }\SpecialCharTok{\textgreater{}} \DecValTok{0}\NormalTok{)}

\CommentTok{\# Visualization: Interest matrix}
\FunctionTok{ggplot}\NormalTok{(interest\_analysis, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ xyz\_campaign\_id, }\AttributeTok{y =} \FunctionTok{as.factor}\NormalTok{(interest))) }\SpecialCharTok{+}
  \FunctionTok{geom\_point}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{size =}\NormalTok{ sales, }\AttributeTok{color =}\NormalTok{ cpa)) }\SpecialCharTok{+}
  \FunctionTok{scale\_color\_gradient}\NormalTok{(}\AttributeTok{low =} \StringTok{"green"}\NormalTok{, }\AttributeTok{high =} \StringTok{"red"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{ (}
    \AttributeTok{title =} \StringTok{"Interest Matrix: Where Did Campaigns Invest?"}\NormalTok{,}
    \AttributeTok{y =} \StringTok{"Interest Code"}\NormalTok{,}
    \AttributeTok{x =} \StringTok{"Campaign"}\NormalTok{,}
    \AttributeTok{color =} \StringTok{"CPA ($)"}\NormalTok{,}
    \AttributeTok{size =} \StringTok{"Sales Vol."}
\NormalTok{  ) }\SpecialCharTok{+}
  \FunctionTok{theme\_minimal}\NormalTok{() }\SpecialCharTok{+}
  \FunctionTok{theme}\NormalTok{(}\AttributeTok{panel.grid.major.x =} \FunctionTok{element\_blank}\NormalTok{())}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{Digital-Marketing-Analysis-RMD_files/figure-latex/20-1.pdf}}

\subsection{Interest Analysis}\label{interest-analysis}

\subsubsection{Campaign 1178 drove the majority of volume --- but at a
cost}\label{campaign-1178-drove-the-majority-of-volume-but-at-a-cost}

From the prior analysis, we already knew \textbf{Campaign 1178} was the
highest spender and that was confirmed by the matrix as the campaign had
by far the most bubbles and the largest bubbles overall. What we did
learn from the matrix is that \textbf{Campaign 1178} has a broad
investment across many interest segments. However, many of these
high-volume bubbles skew yellow to red including some of the bubbles
with the highest sales volume.

\subsubsection{Campaign 916 shows limited investment and narrow
impact}\label{campaign-916-shows-limited-investment-and-narrow-impact}

Likewise, we already knew from the prior analysis that \textbf{Campaign
916} had the lowest investment and the matrix now proves that the
campaign had a narrow scope as few interests were tested, however, all
interests performed well and were in the green.

\subsubsection{Campaign 936 seems to be cost-efficient
overall}\label{campaign-936-seems-to-be-cost-efficient-overall}

Most bubbles under \textbf{Campaign 936} were green and the CPA is
consistently low across many interest segments. Additionally, Several
interests show moderate sales volume with strong efficiency. Campaign
936 appears well-optimized, balancing conversion volume with low
acquisition cost.

\subsubsection{Diminishing returns appear in high-volume
interests}\label{diminishing-returns-appear-in-high-volume-interests}

The largest bubbles in \textbf{Campaign 1178} are often orange/red. This
suggests that as spending increased, CPA increased.

Will including age groups in our segmentation allow us to extract more
robust insights?

Let's first identify the top 5 interests by spending across all
campaigns.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Identification of top 5 interests by spending}
\NormalTok{top\_interest\_codes }\OtherTok{\textless{}{-}}\NormalTok{ df }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{group\_by}\NormalTok{(interest) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{summarise}\NormalTok{(}\AttributeTok{spending =} \FunctionTok{sum}\NormalTok{(Spent)) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{slice\_max}\NormalTok{(spending, }\AttributeTok{n =} \DecValTok{5}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{pull}\NormalTok{(interest)}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#Display of most invested interest codes}
\NormalTok{top\_interest\_codes }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{print}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 16 27 10 29 28
\end{verbatim}

Now, we will create a heat map showing the CPA for each interest in
relation to the age group that it was targeting. This graph will
hopefully provide us insights into what interests performed better or
worse for certain age groups.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Heatmap: Interest x age x campaign saturation}
\NormalTok{cpa\_colors }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\StringTok{"\#1a9641"}\NormalTok{, }\StringTok{"\#ffffbf"}\NormalTok{, }\StringTok{"\#d7191c"}\NormalTok{)}

\NormalTok{df }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{filter}\NormalTok{(interest }\SpecialCharTok{\%in\%}\NormalTok{ top\_interest\_codes) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{group\_by}\NormalTok{ (xyz\_campaign\_id, interest, age) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{summarise}\NormalTok{(}
    \AttributeTok{cpa =} \FunctionTok{sum}\NormalTok{(Spent) }\SpecialCharTok{/} \FunctionTok{sum}\NormalTok{(Approved\_Conversion),}
    \AttributeTok{sales =} \FunctionTok{sum}\NormalTok{(Approved\_Conversion),}
    \AttributeTok{.groups =} \StringTok{"drop"}
\NormalTok{  ) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{ggplot}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ age, }\AttributeTok{y =} \FunctionTok{as.factor}\NormalTok{(interest), }\AttributeTok{fill =}\NormalTok{ cpa)) }\SpecialCharTok{+}
  \FunctionTok{geom\_tile}\NormalTok{(}\AttributeTok{color =} \StringTok{"white"}\NormalTok{, }\AttributeTok{size =} \FloatTok{0.5}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{geom\_text}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{label =}\NormalTok{ sales), }\AttributeTok{color =} \StringTok{"black"}\NormalTok{, }\AttributeTok{size =} \DecValTok{3}\NormalTok{, }\AttributeTok{fontface =} \StringTok{"bold"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{facet\_wrap}\NormalTok{(}\SpecialCharTok{\textasciitilde{}}\NormalTok{ xyz\_campaign\_id) }\SpecialCharTok{+}
  \FunctionTok{scale\_fill\_gradientn}\NormalTok{(}
    \AttributeTok{colors =}\NormalTok{ cpa\_colors,}
    \AttributeTok{name =} \StringTok{"CPA ($)"}
\NormalTok{  ) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}
    \AttributeTok{title =} \StringTok{"Saturation: Interest x Age x Campaign"}\NormalTok{,}
    \AttributeTok{subtitle =} \StringTok{"Color: Cost per Sale (Green = Cheap, Red = Expensive)}\SpecialCharTok{\textbackslash{}n}\StringTok{Number: Total Sales"}\NormalTok{,}
    \AttributeTok{y =} \StringTok{"Interests (Top 5)"}\NormalTok{,}
    \AttributeTok{x =} \StringTok{"Age Range"}
\NormalTok{  ) }\SpecialCharTok{+}
  \FunctionTok{theme\_minimal}\NormalTok{() }\SpecialCharTok{+}
  \FunctionTok{theme}\NormalTok{(}
    \AttributeTok{panel.grid =} \FunctionTok{element\_blank}\NormalTok{(),}
    \AttributeTok{strip.text =} \FunctionTok{element\_text}\NormalTok{(}\AttributeTok{face =} \StringTok{"bold"}\NormalTok{, }\AttributeTok{size =} \DecValTok{12}\NormalTok{)}
\NormalTok{  )}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning: Using `size` aesthetic for lines was deprecated in ggplot2 3.4.0.
## i Please use `linewidth` instead.
## This warning is displayed once every 8 hours.
## Call `lifecycle::last_lifecycle_warnings()` to see where this warning was
## generated.
\end{verbatim}

\pandocbounded{\includegraphics[keepaspectratio]{Digital-Marketing-Analysis-RMD_files/figure-latex/23-1.pdf}}

\subsection{Identified Pattern: 30-34
Range}\label{identified-pattern-30-34-range}

The \textbf{30-34 years} range seems to perform consistently better
across all campaigns, converting more with a lower CPA.

We need to drill down to the individual ad level to see if there are
extremely expensive ads that don't generate returns and waste XYZ
company resources.

\subsection{Ad Classification by
Performance}\label{ad-classification-by-performance}

I adopted the following classification for each ad using the
\textbf{base average CPA (\textasciitilde\$40)} and the number of
conversions:

\begin{itemize}
\tightlist
\item
  \textbf{Zombie (Spends and doesn't sell)}: Didn't convert anyone and
  cost more than \$50
\item
  \textbf{Star (Cheap)}: Produced sales \& CPA below base average
\item
  \textbf{Expensive (Needs Optimization):}: Produced sales \& CPA above
  base average
\item
  \textbf{In Test}: Spending too low to classify
\end{itemize}

Now let's aggregate the data set and classify each ad into one of the
four above categories. After that is complete, we will create a
visualization showing the total sales for each individual ad along with
the amount spent on each ad.Specifically, we are looking for
\textbf{Zombie Ads} which are wasting the company money. Any Zombie ad
should be paused immediately.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Data aggregation by ad}
\NormalTok{df\_ads }\OtherTok{\textless{}{-}}\NormalTok{ df }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{group\_by}\NormalTok{(ad\_id, xyz\_campaign\_id) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{summarise}\NormalTok{(}
    \AttributeTok{spent =} \FunctionTok{sum}\NormalTok{(Spent),}
    \AttributeTok{impressions =} \FunctionTok{sum}\NormalTok{(Impressions),}
    \AttributeTok{clicks =} \FunctionTok{sum}\NormalTok{(Clicks),}
    \AttributeTok{sales =} \FunctionTok{sum}\NormalTok{(Approved\_Conversion),}
    \AttributeTok{ctr =}\NormalTok{ (}\FunctionTok{sum}\NormalTok{(Clicks) }\SpecialCharTok{/} \FunctionTok{sum}\NormalTok{(Impressions)) }\SpecialCharTok{*} \DecValTok{100}\NormalTok{,}
    \AttributeTok{cpa =} \FunctionTok{ifelse}\NormalTok{(sales }\SpecialCharTok{\textgreater{}} \DecValTok{0}\NormalTok{, spent }\SpecialCharTok{/}\NormalTok{ sales, }\ConstantTok{NA}\NormalTok{),}
    \AttributeTok{.groups =} \StringTok{"drop"}
\NormalTok{  )}

\CommentTok{\# Ad classification}
\NormalTok{df\_ads }\OtherTok{\textless{}{-}}\NormalTok{ df\_ads }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{mutate}\NormalTok{(}
    \AttributeTok{status =} \FunctionTok{case\_when}\NormalTok{(}
\NormalTok{      (sales }\SpecialCharTok{==} \DecValTok{0} \SpecialCharTok{\&}\NormalTok{ (spent }\SpecialCharTok{\textgreater{}} \DecValTok{50} \SpecialCharTok{|} \FunctionTok{is.na}\NormalTok{(spent))) }\SpecialCharTok{\textasciitilde{}} \StringTok{"Zombie (Spends and doesn\textquotesingle{}t sell)"}\NormalTok{,}
\NormalTok{      cpa }\SpecialCharTok{\textless{}} \DecValTok{40} \SpecialCharTok{\textasciitilde{}} \StringTok{"Star (Cheap)"}\NormalTok{,}
\NormalTok{      cpa }\SpecialCharTok{\textgreater{}=} \DecValTok{40} \SpecialCharTok{\textasciitilde{}} \StringTok{"Expensive (Needs Optimization)"}\NormalTok{,}
      \ConstantTok{TRUE} \SpecialCharTok{\textasciitilde{}} \StringTok{"In Test (Low Relative Spending)"}
\NormalTok{    )}
\NormalTok{  )}

\CommentTok{\# Visualization: Ad audit}
\NormalTok{df\_ads }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{filter}\NormalTok{(spent }\SpecialCharTok{\textgreater{}} \DecValTok{0}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%}  
  \FunctionTok{ggplot}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ spent, }\AttributeTok{y =}\NormalTok{ sales, }\AttributeTok{color =}\NormalTok{ status)) }\SpecialCharTok{+}
  \FunctionTok{geom\_point}\NormalTok{(}\AttributeTok{alpha =} \FloatTok{0.6}\NormalTok{, }\AttributeTok{size =} \DecValTok{2}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{facet\_wrap}\NormalTok{(}\SpecialCharTok{\textasciitilde{}}\NormalTok{ xyz\_campaign\_id, }\AttributeTok{scales =} \StringTok{"free"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{scale\_color\_manual}\NormalTok{(}\AttributeTok{values =} \FunctionTok{c}\NormalTok{(}
    \StringTok{"Star (Cheap)"} \OtherTok{=} \StringTok{"green4"}\NormalTok{,}
    \StringTok{"Expensive (Needs Optimization)"} \OtherTok{=} \StringTok{"orange"}\NormalTok{,}
    \StringTok{"Zombie (Spends and doesn\textquotesingle{}t sell)"} \OtherTok{=} \StringTok{"red"}\NormalTok{,}
    \StringTok{"In Test (Low Relative Spending)"} \OtherTok{=} \StringTok{"grey"}
\NormalTok{  )) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}
    \AttributeTok{title =} \StringTok{"Ad Audit (ad\_id)"}\NormalTok{,}
    \AttributeTok{subtitle =} \StringTok{"Red dots should be paused immediately"}\NormalTok{,}
    \AttributeTok{x =} \StringTok{"Total Investment ($)"}\NormalTok{,}
    \AttributeTok{y =} \StringTok{"Total Sales"}
\NormalTok{  ) }\SpecialCharTok{+}
  \FunctionTok{theme\_minimal}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{Digital-Marketing-Analysis-RMD_files/figure-latex/24-1.pdf}}

\subsection{Alert: Zombie Ads}\label{alert-zombie-ads}

There are many ads to pause in \textbf{Campaign 1178} and several to
optimize. \textbf{Campaign 936} also has a significant number of
problematic ads.

Let's list the zombie ads with a recommendation to completely pause
them, and segment the ``star'' ads to understand where we got it right.
First, we'll count the quantity and total spent for the zombie ads for
each campaign.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Counting zombie ads by camaign }
\NormalTok{df\_ads }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{filter}\NormalTok{(status }\SpecialCharTok{==} \StringTok{"Zombie (Spends and doesn\textquotesingle{}t sell)"}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{group\_by}\NormalTok{(xyz\_campaign\_id) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{summarise}\NormalTok{(}
    \AttributeTok{qty\_zombies =} \FunctionTok{n}\NormalTok{(),}
    \AttributeTok{total\_spent =} \FunctionTok{sum}\NormalTok{(spent)}
\NormalTok{  )}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 2 x 3
##   xyz_campaign_id qty_zombies total_spent
##             <dbl>       <int>       <dbl>
## 1             936           7        584.
## 2            1178          80       9858.
\end{verbatim}

\subsection{Savings Opportunity}\label{savings-opportunity}

If XYZ company paused \textbf{today} all \textbf{87 zombie ads}, the
immediate savings would be \textbf{\$10,442}.

Let's examine the top 10 to identify the biggest wasters.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Top 10 zombie ads by spending}
\NormalTok{df\_ads }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{filter}\NormalTok{(status }\SpecialCharTok{==} \StringTok{"Zombie (Spends and doesn\textquotesingle{}t sell)"}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{arrange}\NormalTok{(}\FunctionTok{desc}\NormalTok{(spent)) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{select}\NormalTok{(ad\_id, xyz\_campaign\_id, spent, impressions, clicks) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{head}\NormalTok{(}\DecValTok{10}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 10 x 5
##      ad_id xyz_campaign_id spent impressions clicks
##      <dbl>           <dbl> <dbl>       <dbl>  <dbl>
##  1 1122265            1178  542.     1428421    367
##  2 1122304            1178  402.     1111156    282
##  3 1122112            1178  390.     1083259    276
##  4 1122209            1178  333.      890295    227
##  5 1314389            1178  319.     1114711    224
##  6 1122202            1178  296.      906151    202
##  7 1122127            1178  288.      822023    194
##  8 1122197            1178  235.      662249    163
##  9 1122203            1178  226.      699314    164
## 10 1122200            1178  195.      559554    139
\end{verbatim}

\subsection{Waste Concentration}\label{waste-concentration}

The \textbf{top 10} zombie ads represent just over \textbf{30\% of total
spending} wasted in this category. That is a lot of waste centered
around a few specific ads.

Let's dig deeper and determine if there is a difference in demographic
profile between who the star ads and the zombie ads are targeting. We've
already determined that the \textbf{30-34 years} range is promising, I
wonder if the star ads targeted more of the younger audience while the
zombie ads targeted the higher age range.

We will create a visualization to compare the two types of ads by the
age range they targeted and the gender.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Joining original data with status classification}
\NormalTok{df\_classified }\OtherTok{\textless{}{-}}\NormalTok{ df }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{inner\_join}\NormalTok{(df\_ads }\SpecialCharTok{\%\textgreater{}\%}  \FunctionTok{select}\NormalTok{(ad\_id, status, cpa), }\AttributeTok{by =} \StringTok{"ad\_id"}\NormalTok{)}

\CommentTok{\# Comparison: Stars vs Zombies by demographic profile}
\NormalTok{df\_classified }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{filter}\NormalTok{(status }\SpecialCharTok{\%in\%} \FunctionTok{c}\NormalTok{(}\StringTok{"Star (Cheap)"}\NormalTok{, }\StringTok{"Zombie (Spends and doesn\textquotesingle{}t sell)"}\NormalTok{)) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{group\_by}\NormalTok{(status, age, gender) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{summarise}\NormalTok{(}\AttributeTok{total =} \FunctionTok{n}\NormalTok{(), }\AttributeTok{.groups =} \StringTok{"drop"}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{ggplot}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ age, }\AttributeTok{y =}\NormalTok{ total, }\AttributeTok{fill =}\NormalTok{ gender)) }\SpecialCharTok{+}
  \FunctionTok{geom\_col}\NormalTok{(}\AttributeTok{position =} \StringTok{"dodge"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{facet\_wrap}\NormalTok{(}\SpecialCharTok{\textasciitilde{}}\NormalTok{ status) }\SpecialCharTok{+}
  \FunctionTok{scale\_fill\_brewer}\NormalTok{(}\AttributeTok{palette =} \StringTok{"Set1"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}
    \AttributeTok{title =} \StringTok{"Battle of Profiles: Stars vs Zombies"}\NormalTok{,}
    \AttributeTok{subtitle =} \StringTok{"Where are Zombies missing the mark? (Probabely wrong audience)"}\NormalTok{,}
    \AttributeTok{y =} \StringTok{"Number of Ads Run"}\NormalTok{,}
    \AttributeTok{x =} \StringTok{"Age Range"}
\NormalTok{  ) }\SpecialCharTok{+}
  \FunctionTok{theme\_minimal}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{Digital-Marketing-Analysis-RMD_files/figure-latex/27-1.pdf}}

\subsection{Clear Demographic Pattern}\label{clear-demographic-pattern}

Our hypothesis seems to be correct:

\textbf{Star Ads}:

\begin{itemize}
\tightlist
\item
  Target the \textbf{30-34 years} range (already identified earlier as
  promising)
\item
  Focus more on \textbf{male} audience
\end{itemize}

\textbf{Zombie Ads}:

\begin{itemize}
\tightlist
\item
  Focus a higher percentage on the \textbf{40-49 years} range (compared
  to the star ads)
\item
  Focus more on the \textbf{female} audience overall
\end{itemize}

This suggests the problem could be either the age range or the gender
they are targeting.

Given the significant disparity in the age range that each type of ad
targeted, I hypothesize the problem relates more towards the age range
the ads are targeting compared to the gender.

Let's now analyze how Star and Zombie ads differ in \textbf{interest}
segmentation.

We will first group the top 10 interests by the amount invested for each
type of ad (Star \& Zombie). Then we will visualize if the highest
investments were in similar interests for the star and zombie ads.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Identification of top 10 interests in each cluster}
\NormalTok{top\_interest\_stars }\OtherTok{\textless{}{-}}\NormalTok{ df\_classified }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{filter}\NormalTok{(status }\SpecialCharTok{==} \StringTok{"Star (Cheap)"}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{group\_by}\NormalTok{(interest) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{summarise}\NormalTok{(}\AttributeTok{value =} \FunctionTok{sum}\NormalTok{(Approved\_Conversion)) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{mutate}\NormalTok{(}
    \AttributeTok{type =} \StringTok{"Stars (Focus: Sales)"}\NormalTok{,}
    \AttributeTok{share =}\NormalTok{ value }\SpecialCharTok{/} \FunctionTok{sum}\NormalTok{(value)}
\NormalTok{  ) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{slice\_max}\NormalTok{(share, }\AttributeTok{n =} \DecValTok{10}\NormalTok{)}

\NormalTok{top\_interests\_zombies }\OtherTok{\textless{}{-}}\NormalTok{ df\_classified }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{filter}\NormalTok{(status }\SpecialCharTok{==} \StringTok{"Zombie (Spends and doesn\textquotesingle{}t sell)"}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{group\_by}\NormalTok{(interest) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{summarise}\NormalTok{(}\AttributeTok{value =} \FunctionTok{sum}\NormalTok{(Spent)) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{mutate}\NormalTok{(}
    \AttributeTok{type =} \StringTok{"Zombies (Focus: Waste)"}\NormalTok{,}
    \AttributeTok{share =}\NormalTok{ value }\SpecialCharTok{/} \FunctionTok{sum}\NormalTok{(value)}
\NormalTok{  ) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{slice\_max}\NormalTok{(share, }\AttributeTok{n =} \DecValTok{10}\NormalTok{)}

\CommentTok{\# Ordering based on star success}
\NormalTok{interest\_order }\OtherTok{\textless{}{-}}\NormalTok{ top\_interest\_stars }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{arrange}\NormalTok{(share) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{pull}\NormalTok{(interest)}


\CommentTok{\# Data preparation for visualization}
\NormalTok{plot\_data }\OtherTok{\textless{}{-}} \FunctionTok{bind\_rows}\NormalTok{(top\_interest\_stars, top\_interests\_zombies) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{mutate}\NormalTok{(}\AttributeTok{interest =} \FunctionTok{factor}\NormalTok{(interest, }\AttributeTok{levels =}\NormalTok{ interest\_order)) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{filter}\NormalTok{(}\SpecialCharTok{!}\FunctionTok{is.na}\NormalTok{(interest))}

\CommentTok{\# Comparative visualization}
\FunctionTok{ggplot}\NormalTok{(plot\_data, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ interest, }\AttributeTok{y =}\NormalTok{ share, }\AttributeTok{fill =}\NormalTok{ type)) }\SpecialCharTok{+}
  \FunctionTok{geom\_col}\NormalTok{() }\SpecialCharTok{+}
  \FunctionTok{coord\_flip}\NormalTok{() }\SpecialCharTok{+}
  \FunctionTok{facet\_wrap}\NormalTok{(}\SpecialCharTok{\textasciitilde{}}\NormalTok{ type, }\AttributeTok{scales =} \StringTok{"free\_x"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{scale\_y\_continuous}\NormalTok{(}\AttributeTok{labels =}\NormalTok{ scales}\SpecialCharTok{::}\FunctionTok{percent\_format}\NormalTok{(}\AttributeTok{accuracy =} \DecValTok{1}\NormalTok{)) }\SpecialCharTok{+}
  \FunctionTok{scale\_fill\_manual}\NormalTok{(}\AttributeTok{values =} \FunctionTok{c}\NormalTok{(}\StringTok{"forestgreen"}\NormalTok{, }\StringTok{"firebrick"}\NormalTok{)) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}
    \AttributeTok{title =} \StringTok{"Share Comparison: Where Do Resources Go?"}\NormalTok{,}
    \AttributeTok{subtitle =} \StringTok{"Interests ordered by Star success}\SpecialCharTok{\textbackslash{}n}\StringTok{See if your Top Sellers are also the biggest wastes in Zombies"}\NormalTok{,}
    \AttributeTok{x =} \StringTok{"Interest Code (Ordered by Success)"}\NormalTok{,}
    \AttributeTok{y =} \StringTok{"Share (\%)"}\NormalTok{,}
    \AttributeTok{fill =} \ConstantTok{NULL}
\NormalTok{  ) }\SpecialCharTok{+}
  \FunctionTok{theme\_minimal}\NormalTok{() }\SpecialCharTok{+}
  \FunctionTok{theme}\NormalTok{(}\AttributeTok{legend.position =} \StringTok{"none"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{Digital-Marketing-Analysis-RMD_files/figure-latex/28-1.pdf}}

\subsection{Interest Overlap}\label{interest-overlap}

It's notable that the \textbf{top 4 spending percentages} for Star ads
were also high spenders for Zombie ads.This is especially evident with
\textbf{Interest 16} which was the largest spender for the Star ads and
was also about 10\% of the investment for Zombie ads.

This reinforces the idea that the differences in success between the two
groups of ads is due to the difference in \textbf{age segmentation}
(40-49 years vs 30-34 years), not the interests themselves.

Let's identify which interests work well when properly segmented but
fail when applied to the wrong audience. In order to do this, we will
make a matrix graph which shows the \textbf{risk vs reward} for
interests

\textbf{X-axes (Stars)} - How good this interest is when it works

\textbf{Y-axis (Zombies)} - How expensive this interest is when it fails

Each point will show us \textbf{when this interest works, how much do we
gain and when it doesn't, how much do we burn?}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Identification of common interests between stars and zombies}
\NormalTok{common\_interests }\OtherTok{\textless{}{-}}\NormalTok{ df\_classified }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{group\_by}\NormalTok{(interest) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{summarise}\NormalTok{(}
    \AttributeTok{star\_sales =} \FunctionTok{sum}\NormalTok{(Approved\_Conversion[status }\SpecialCharTok{==} \StringTok{"Star (Cheap)"}\NormalTok{]),}
    \AttributeTok{zombie\_spent =} \FunctionTok{sum}\NormalTok{(Spent[status }\SpecialCharTok{==} \StringTok{"Zombie (Spends and doesn\textquotesingle{}t sell)"}\NormalTok{]),}
    \AttributeTok{.groups =} \StringTok{"drop"}
\NormalTok{  ) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{filter}\NormalTok{(star\_sales }\SpecialCharTok{\textgreater{}} \DecValTok{0}\NormalTok{, zombie\_spent }\SpecialCharTok{\textgreater{}} \DecValTok{0}\NormalTok{)}

\CommentTok{\# Median calucation for quadrants}
\NormalTok{median\_sales }\OtherTok{\textless{}{-}} \FunctionTok{median}\NormalTok{(common\_interests}\SpecialCharTok{$}\NormalTok{star\_sales)}
\NormalTok{median\_spent }\OtherTok{\textless{}{-}} \FunctionTok{median}\NormalTok{(common\_interests}\SpecialCharTok{$}\NormalTok{zombie\_spent)}

\CommentTok{\# Visualization: Potential vs waste matrix}
\FunctionTok{ggplot}\NormalTok{(common\_interests, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ star\_sales, }\AttributeTok{y =}\NormalTok{ zombie\_spent)) }\SpecialCharTok{+}
  \FunctionTok{annotate}\NormalTok{(}\StringTok{"rect"}\NormalTok{, }\AttributeTok{xmin =}\NormalTok{ median\_sales, }\AttributeTok{xmax =} \ConstantTok{Inf}\NormalTok{, }\AttributeTok{ymin =}\NormalTok{ median\_spent, }\AttributeTok{ymax =} \ConstantTok{Inf}\NormalTok{,}
           \AttributeTok{fill =} \StringTok{"orange"}\NormalTok{, }\AttributeTok{alpha =} \FloatTok{0.1}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{annotate}\NormalTok{(}\StringTok{"rect"}\NormalTok{, }\AttributeTok{xmin =}\NormalTok{ median\_sales, }\AttributeTok{xmax =} \ConstantTok{Inf}\NormalTok{, }\AttributeTok{ymin =} \SpecialCharTok{{-}}\ConstantTok{Inf}\NormalTok{, }\AttributeTok{ymax =}\NormalTok{ median\_spent,}
           \AttributeTok{fill =} \StringTok{"green"}\NormalTok{, }\AttributeTok{alpha =} \FloatTok{0.1}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{geom\_point}\NormalTok{(}\AttributeTok{color =} \StringTok{"purple"}\NormalTok{, }\AttributeTok{size =} \DecValTok{3}\NormalTok{, }\AttributeTok{alpha =} \FloatTok{0.7}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{geom\_text}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{label =}\NormalTok{ interest), }\AttributeTok{vjust =} \SpecialCharTok{{-}}\FloatTok{0.5}\NormalTok{, }\AttributeTok{size =} \DecValTok{3}\NormalTok{, }\AttributeTok{check\_overlap =} \ConstantTok{TRUE}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{geom\_vline}\NormalTok{(}\AttributeTok{xintercept =}\NormalTok{ median\_sales, }\AttributeTok{linetype =} \StringTok{"dashed"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{geom\_hline}\NormalTok{(}\AttributeTok{yintercept =}\NormalTok{ median\_spent, }\AttributeTok{linetype =} \StringTok{"dashed"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{annotate}\NormalTok{(}\StringTok{"text"}\NormalTok{, }\AttributeTok{x =} \FunctionTok{max}\NormalTok{(common\_interests}\SpecialCharTok{$}\NormalTok{star\_sales),}
           \AttributeTok{y =} \FunctionTok{max}\NormalTok{(common\_interests}\SpecialCharTok{$}\NormalTok{zombie\_spent),}
           \AttributeTok{label =} \StringTok{"Adjust Segmentation"}\NormalTok{, }\AttributeTok{hjust =} \DecValTok{1}\NormalTok{, }\AttributeTok{vjust =} \DecValTok{1}\NormalTok{,}
           \AttributeTok{fontface =} \StringTok{"bold"}\NormalTok{, }\AttributeTok{size =} \DecValTok{3}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{annotate}\NormalTok{(}\StringTok{"text"}\NormalTok{, }\AttributeTok{x =} \FunctionTok{max}\NormalTok{(common\_interests}\SpecialCharTok{$}\NormalTok{star\_sales), }\AttributeTok{y =} \DecValTok{0}\NormalTok{,}
           \AttributeTok{label =} \StringTok{"Scale"}\NormalTok{, }\AttributeTok{hjust =} \DecValTok{1}\NormalTok{, }\AttributeTok{vjust =} \DecValTok{0}\NormalTok{, }\AttributeTok{fontface =} \StringTok{"bold"}\NormalTok{, }\AttributeTok{size =} \DecValTok{3}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}
    \AttributeTok{title =} \StringTok{"Common Interests Matrix: Where to Adjust?"}\NormalTok{,}
    \AttributeTok{subtitle =} \StringTok{"X{-}axis: Sales Potential (Stars) | Y{-}axis: Cost of Error (Zombies)"}\NormalTok{,}
    \AttributeTok{x =} \StringTok{"Sales Volume (When It Works)"}\NormalTok{,}
    \AttributeTok{y =} \StringTok{"Money Wasted (When It Fails)"}
\NormalTok{  ) }\SpecialCharTok{+}
  \FunctionTok{theme\_minimal}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{Digital-Marketing-Analysis-RMD_files/figure-latex/29-1.pdf}}

\subsection{Critical Insights}\label{critical-insights}

Based on the graph, we can identify how successful the interests are and
answer the question of \textbf{which interests are failing because
they're bad and which are failing because they're misused?}

We'll want to characterize each interest by the following:

\begin{itemize}
\item
  \textbf{Bad interests} → cut them
\item
  \textbf{Good but misused interests} → adjust segmentation
\item
  \textbf{Good and efficient interests} → scale hard
\end{itemize}

Let's look at each quadrant specifically:

\textbf{Bottom-right --- Scale}

\begin{itemize}
\tightlist
\item
  \textbf{High sales, low waste}
\item
  These interests convert well and don't burn much budget when they fail
\item
  We should look to increase spending on these interests
\end{itemize}

\textbf{Top-right --- Adjust Segmentation}

\begin{itemize}
\tightlist
\item
  \textbf{High sales, high waste}
\item
  These interests can clearly work but are expensive when they are
  mis-targeted
\item
  We should look to tighten targeting around these interests
\end{itemize}

\textbf{Bottom-left --- Ignore or deprioritize}

\begin{itemize}
\tightlist
\item
  \textbf{Low sales, low waste}
\item
  These interests are safe but unimpactful
\item
  We are fine to pause or keep with minimal budget
\end{itemize}

\textbf{Top-left --- Cut}

\begin{itemize}
\tightlist
\item
  \textbf{Low sales, high waste}
\item
  Limited upside and real downside
\item
  We should kill off or completely rethink these interests
\end{itemize}

\subsection{Statistical Validation: Difference by Age
Range}\label{statistical-validation-difference-by-age-range}

Next, let's look to see if we can validate our observation that the
\textbf{30-34} age range performs better than the other age ranges. To
do so, we will determine if the \textbf{30-34} age range is
\textbf{statistically different} from the others in terms of conversion
rate.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Data preparation for statistical test}
\NormalTok{age\_data\_general }\OtherTok{\textless{}{-}}\NormalTok{ df }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{group\_by}\NormalTok{(age) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{summarise}\NormalTok{(}
    \AttributeTok{sales =} \FunctionTok{sum}\NormalTok{(Approved\_Conversion),}
    \AttributeTok{non\_sales =} \FunctionTok{sum}\NormalTok{(Clicks) }\SpecialCharTok{{-}} \FunctionTok{sum}\NormalTok{(Approved\_Conversion),}
    \AttributeTok{total\_attempts =} \FunctionTok{sum}\NormalTok{(Clicks)}
\NormalTok{  )}

\NormalTok{sales }\OtherTok{\textless{}{-}}\NormalTok{ age\_data\_general}\SpecialCharTok{$}\NormalTok{sales}
\NormalTok{attempts }\OtherTok{\textless{}{-}}\NormalTok{ age\_data\_general}\SpecialCharTok{$}\NormalTok{total\_attempts}

\FunctionTok{names}\NormalTok{(sales) }\OtherTok{\textless{}{-}}\NormalTok{ age\_data\_general}\SpecialCharTok{$}\NormalTok{age}
\FunctionTok{names}\NormalTok{(attempts) }\OtherTok{\textless{}{-}}\NormalTok{ age\_data\_general}\SpecialCharTok{$}\NormalTok{total\_attempts}

\CommentTok{\# Pairwise proportion test with Bonferroni correction}
\NormalTok{age\_test\_corrected }\OtherTok{\textless{}{-}} \FunctionTok{pairwise.prop.test}\NormalTok{(}
  \AttributeTok{x =}\NormalTok{ sales,}
  \AttributeTok{n =}\NormalTok{ attempts,}
  \AttributeTok{p.adjust.method =} \StringTok{"bonferroni"}
\NormalTok{)}

\FunctionTok{print}\NormalTok{(age\_test\_corrected)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Pairwise comparisons using Pairwise comparison of proportions 
## 
## data:  sales out of attempts 
## 
##       30-34   35-39   40-44 
## 35-39 3.3e-12 -       -     
## 40-44 < 2e-16 0.0378  -     
## 45-49 < 2e-16 2.9e-11 0.0014
## 
## P value adjustment method: bonferroni
\end{verbatim}

\subsection{Result: Statistical Difference
Confirmed}\label{result-statistical-difference-confirmed}

The \textbf{30-34 years} range is \textbf{statistically different} from
other age ranges in terms of conversion rate (p \textless{} 0.05 after
Bonferroni correction) so we can reject the null hypothesis.

This validates our previous qualitative observation.

\subsection{Statistical Validation: Difference by
Gender}\label{statistical-validation-difference-by-gender}

Now let's do a separate statistical test to determine if there is a
significant difference in \textbf{CPA trend} between genders?

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Data preparation (only ads that converted)}
\NormalTok{cpa\_gender\_data }\OtherTok{\textless{}{-}}\NormalTok{ df }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{filter}\NormalTok{(Approved\_Conversion }\SpecialCharTok{\textgreater{}} \DecValTok{0}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{mutate}\NormalTok{(}\AttributeTok{cpa =}\NormalTok{ Spent }\SpecialCharTok{/}\NormalTok{ Approved\_Conversion)}

\CommentTok{\# Kruskal{-}Wallis non{-}parametric test}
\FunctionTok{kruskal.test}\NormalTok{(cpa }\SpecialCharTok{\textasciitilde{}}\NormalTok{ gender, }\AttributeTok{data =}\NormalTok{ cpa\_gender\_data)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Kruskal-Wallis rank sum test
## 
## data:  cpa by gender
## Kruskal-Wallis chi-squared = 11.7, df = 1, p-value = 0.0006251
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Visualization of CPA distribution by gender}
\FunctionTok{ggplot}\NormalTok{(cpa\_gender\_data, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ gender, }\AttributeTok{y =}\NormalTok{ cpa)) }\SpecialCharTok{+}
  \FunctionTok{geom\_boxplot}\NormalTok{(}\AttributeTok{fill =} \FunctionTok{c}\NormalTok{(}\StringTok{"\#F8766D"}\NormalTok{, }\StringTok{"\#00BFC4"}\NormalTok{), }\AttributeTok{alpha =} \FloatTok{0.7}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}
    \AttributeTok{title =} \StringTok{"Statistical Distribution of CPA by Gender"}\NormalTok{,}
    \AttributeTok{x =} \StringTok{"Gender"}\NormalTok{,}
    \AttributeTok{y =} \StringTok{"CPA ($)"}
\NormalTok{  ) }\SpecialCharTok{+}
  \FunctionTok{theme\_minimal}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{Digital-Marketing-Analysis-RMD_files/figure-latex/32-1.pdf}}

\subsection{Result: Cost Difference by
Gender}\label{result-cost-difference-by-gender}

There is \textbf{statistical evidence} that \textbf{females} costs more
than \textbf{males} to convert (p \textless{} 0.05).

It would be a smart idea to target \textbf{males} more heavily going
forward.

\section{Executive Report: Conclusions and
Recommendations}\label{executive-report-conclusions-and-recommendations}

\subsection{1. Executive Summary}\label{executive-summary}

Data analysis identified that \textbf{Campaign 1178} shows a cost per
sale drastically higher than other campaigns. The higher cost is not due
to the marketing channel itself, but do to the \textbf{inefficiency in
audience segmentation} and the \textbf{usage of ineffective ads}.

There is a clear opportunity to \textbf{reduce costs while maintaining
sales volume} by concentrating the budget on proven buyer demographic
profiles.

\subsection{2. Problem Diagnosis}\label{problem-diagnosis}

We identified three main factors draining the company's budget:

\subsubsection{2.1. Demographic
Dispersion}\label{demographic-dispersion}

\textbf{Campaign 1178} is spending significant budget on the
\textbf{40-49 years} age range. Statistical tests confirm this group
does not convert sales as efficiently as the \textbf{30-34 years} age
range.

\subsubsection{2.2. Ads with Total Waste}\label{ads-with-total-waste}

We mapped a group of \textbf{87 ads} (identified as ``Zombies'') that
consistently consume budget without having generated \textbf{any sales}.
The accumulation of these expenses represents \textbf{\$10,442} of total
waste, with the top 10 accounting for \textbf{30\%} of this amount.

\subsubsection{2.3. Inadequate Interest
Segmentation}\label{inadequate-interest-segmentation}

Several interests that \textbf{work well} for the younger audience
(30-34 years) are being shown to older audiences, where they don't
perform, generating a \textbf{false negative} about the quality of these
interests.

\subsection{3. High Performance Profile}\label{high-performance-profile}

The ideal customer profile, which brings the \textbf{highest return on
investment}, has the following characteristics:

\subsubsection{Ideal Target Audience
Characteristics:}\label{ideal-target-audience-characteristics}

\begin{itemize}
\tightlist
\item
  \textbf{Age Range}: \textbf{30 to 34 years} (statistically superior
  performance to all other ranges)
\item
  \textbf{Behavior}: Specific interests (codes 29, 16, 10, 15, 20) when
  targeted to this young audience have shown to convert at low cost and
  at high frequency)
\item
  \textbf{Gender Differentiation}: There is a statistically significant
  difference in CPA between genders, which should be considered in
  allocation
\end{itemize}

\subsection{4. Recommended Action Plan}\label{recommended-action-plan}

\subsubsection{4.1. Short-Term Actions (Immediate
Implementation)}\label{short-term-actions-immediate-implementation}

\begin{enumerate}
\def\labelenumi{\alph{enumi})}
\tightlist
\item
  Pause Inefficient Ads
\end{enumerate}

\textbf{Estimated savings: \$10,442}

\begin{itemize}
\tightlist
\item
  Immediately stop running the \textbf{87 Zombie ads} listed in the
  technical report
\item
  Prioritize the top 10 that account for 30\% of waste
\end{itemize}

\begin{enumerate}
\def\labelenumi{\alph{enumi})}
\setcounter{enumi}{1}
\tightlist
\item
  Age Restriction
\end{enumerate}

\begin{itemize}
\tightlist
\item
  Change \textbf{Campaign 1178} configuration to \textbf{exclude} ad
  display for the \textbf{40 to 49 years} range
\item
  This range showed high cost without proportional return
\end{itemize}

\subsubsection{4.2. Medium-Term Actions
(Strategic)}\label{medium-term-actions-strategic}

\begin{enumerate}
\def\labelenumi{\alph{enumi})}
\tightlist
\item
  Budget Reallocation
\end{enumerate}

\begin{itemize}
\tightlist
\item
  Direct the budget saved from the above actions to \textbf{intensify
  exposure} in the \textbf{30 to 34 years} range, where the probability
  of sale is proven higher
\end{itemize}

\begin{enumerate}
\def\labelenumi{\alph{enumi})}
\setcounter{enumi}{1}
\tightlist
\item
  Focused Segmentation
\end{enumerate}

\begin{itemize}
\tightlist
\item
  Create \textbf{new ad sets} focusing on the high-performance interests
  (29, 16, 10, 15, 20)
\item
  Restrict these ads \textbf{exclusively to the 30 to 34 years audience}
  to avoid new waste
\item
  Consider CPA difference by gender in proportional budget allocation
  (more budget to the male audience).
\end{itemize}

\begin{enumerate}
\def\labelenumi{\alph{enumi})}
\setcounter{enumi}{2}
\tightlist
\item
  Continuous Testing and Learning
\end{enumerate}

\begin{itemize}
\tightlist
\item
  Implement weekly monitoring of ads classified as ``Expensive''
\item
  Establish a \textbf{\$50 test spending limit} before classifying an ad
  as Zombie
\item
  Create a quarterly review process to identify new promising interests
\end{itemize}

\subsection{5. Expected Impact}\label{expected-impact}

With full implementation of recommendations, we estimate:

\begin{itemize}
\tightlist
\item
  \textbf{Immediate cost reduction}: \textasciitilde\$10,442 (Zombie
  pause)
\item
  \textbf{CPA improvement}: 40-50\% reduction by focusing on 30-34
  audience
\item
  \textbf{Maintenance or increase in sales volume}: Through intelligent
  budget reallocation
\item
  \textbf{Improved ROI}: Concentration on proven profitable segments
\end{itemize}

\end{document}
